[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/app/*"
  status = 200
  to = "/.netlify/functions/app/:splat"
[build]
  command = "echo 'Building Functions'"